### ISSUE TITLE
Some currency not worked

### ISSUE THREAD

**Issue by vigneshkurinjie** [philwinkle/Philwinkle_Fixerio#11]
Hi There,

I used your extension. It's working perfectly. But I have some problem while using it. It can't have all currency conversions.

I need to convert USD -> AED and USD -> SAR.

It displays an empty result. 

How can I get this ?

Thanks in advance.

**Comment by philwinkle** [comment]
AED and SAR are not tracked by the European Central Bank, which is what Fixer.io uses as its data source. Sorry for that!

http://www.ecb.europa.eu/stats/exchange/eurofxref/html/index.en.html
