### ISSUE TITLE
Add possibility to set a proxy

### ISSUE THREAD

**Issue by aurmil** [philwinkle/Philwinkle_Fixerio#15]
hello
I have to specify a proxy to cURL for my server to correctly make the request
problem is whatever we do before the request() call, Varien_Http_Client will overwrite adapter if curl extension is loaded
so may be use directly Zend_Http_Client instead (as there is no real value in using the Varien one as far as I can see on this use case), set adapter to curl and add the possiblity to specify a proxy
=> what about people needing to use a proxy but not with curl...? default adapter is Zend_Http_Client_Adapter_Socket => set the proxy through setStreamContext()?
thanks

**Comment by philwinkle** [comment]
This sounds like a smart idea. I would typically have proxied with a daemon - but this is possible. I'd like to see what you come up with, otherwise we'll open it as a feature issue for future dev when I have some free time.

**Comment by aurmil** [comment]
I admit that my knowledge in system & network are basic
I don't manage the hosting, it's done by an external hosting provider working for the group I work for
the server I use must use a proxy to make outgoing requests
