### ISSUE TITLE
Not all currencies work

### ISSUE THREAD

**Issue by samisaad** [philwinkle/Philwinkle_Fixerio#17]
Hello, I Have added the Fixerio and made the adjustments on the backend in configuration, and then went to manage currency rates to import, but most of the currencies don't get retrieved. Can you help, please?

**Comment by philwinkle** [comment]
The only rates which work are those published by the European Central Bank, as Fixer requires the ECB rates in order to function.

http://www.ecb.europa.eu/stats/exchange/eurofxref/html/index.en.html
