### ISSUE TITLE
Composer friendly

### ISSUE THREAD

**Issue by omosur** [philwinkle/Philwinkle_Fixerio#18]
Please, add your repository to packagist.org, i saw another yours package but only for magento 2.

**Comment by jacquesbh** [comment]
Ping @philwinkle :) 

It would be great!

Thank you.

**Comment by philwinkle** [comment]
@jacquesbh as we're seeing broader community support on this I'd suggest that someone contribute this functionality! I'll ping Twitter :)

**Comment by jacquesbh** [comment]
There is nothing to do, just submit your package!

https://packagist.org/packages/submit :)

<3

Jacques Bodin-Hullin

-- 
Monsieur Biz <https://monsieurbiz.com>
@jacquesbh <https://twitter.com/jacquesbh>
+33 (0)6 75 54 11 97
GPG : https://keybase.io/jacquesbh

🦄

Le mer. 2 mai 2018 à 16:10, Phillip Jackson <notifications@github.com> a
écrit :

**Comment by philwinkle** [comment]
@jacquesbh oh shoot you're right I already have a composer.json!!!

**Comment by philwinkle** [comment]
@jacquesbh https://packagist.org/packages/philwinkle/fixerio done

**Comment by jacquesbh** [comment]
Lovely.

Jacques Bodin-Hullin

-- 
Monsieur Biz <https://monsieurbiz.com>
@jacquesbh <https://twitter.com/jacquesbh>
+33 (0)6 75 54 11 97
GPG : https://keybase.io/jacquesbh

🦄

Le mer. 2 mai 2018 à 16:25, Phillip Jackson <notifications@github.com> a
écrit :
