### ISSUE TITLE
Changes API need access key

### ISSUE THREAD

**Issue by btekbtek** [philwinkle/Philwinkle_Fixerio#19]
Hi 

Any plans with update. Fixer.io use now plans and access keys.

Free plan for 1000/m
New links should look like this:
http://data.fixer.io/latest?base=GBP&symbols=AUD.

**Comment by philwinkle** [comment]
Hi there @btekbtek - feel free to submit as a PR. The change would be in this file:

https://github.com/philwinkle/Philwinkle_Fixerio/blob/master/app/code/community/Philwinkle/Fixerio/Model/Import.php#L5

**Comment by philwinkle** [comment]
Closed with #21
