### ISSUE TITLE
Currency Rate could not received  from https://api.fixer.io/....

### ISSUE THREAD

**Issue by aauerswald** [philwinkle/Philwinkle_Fixerio#6]
Hello,

when I want to get the actual currency rate from fixer.io I always get a error message:

"Currency Rate could not received  from https://api.fixer.io/latest?base=EUR&symbols=USD"

When I open that URL in the browser I get these:

{"base":"EUR","date":"2015-12-22","rates":{"USD":1.0952}}

I am not sure why it doesn't work. All seems to be fine. Please Help!

**Comment by philwinkle** [comment]
I can't reproduce. Please submit detailed repro steps and feel free to reopen at that time.

**Comment by iknowfoobar** [comment]
I am getting the same problem as this. After adding a bit of debugging to this module the exact Exception coming from the `Varien_Http_Client` when trying to pull the rates is `Unable to read response, or response is empty`

It appears to be a problem with SSL, the API will only work with browsers or servers that support SNI which our server doesn't. The only way I can see to remedy this is to manually change the plugin to use the http version of the API or ask the providers of the API to support clients that don't support SNI.

**Comment by philwinkle** [comment]
@iknowfoobar because SNI is required by the Fixer.io service you would need to request this from their platform. It is also an open-source Heroku app so you could conceivably host it yourself.
