### ISSUE TITLE
cron is updating Webservicex only

### ISSUE THREAD

**Issue by webscot** [philwinkle/Philwinkle_Fixerio#8]
Problem. Apparently cron is updating Webservicex only. I made the change using your files only to find that 24 hours later, the Fixer.io rates were overwritten again with all par 1.0 values from Webservicex. What is the fix for this?

**Comment by philwinkle** [comment]
I believe you have to set in the admin which to update on the Cron.

**Comment by webscot** [comment]
Yes. I did find that to be the case. Thank you for responding.
